name: Release packages

on:
  release:
    types: [release, prerelease]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Cache NPM dependencies
        uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: npm-cache-release-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            npm-cache-release-
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
        env:
          NODE_ENV: production
      - name: Publish
        run: yarn lerna publish from-package --no-verify-access --yes
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
